### ISSUE TITLE
I am working on a Awesome-Python-HTMX, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [Tobi-De/fuzzy-couscous#31]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create awesome-python-htmx; a collection of active tools/libraries/projects in that space. Your project seems like an obvious thing to include. In fact, I had never heard of it before, but seemingly you have already beaten us to the punch on building out an opinionated template for the PyHAT stack :sweat_smile: . I have included it under a "templates" section.

If you would participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated!

**Comment by benjamin-kirkbride** [comment]
I'm also going to include https://oluwatobi.dev/blog/posts/htmx-support-in-pycharm, super cool!

**Comment by Tobi-De** [comment]
Wow, great project and initiative, I love the spirit and the stack and the name is definitely better than what I have for my own project right now. 
Two of the best django htmx resources I know of that seem to be missing on the repo right now are

- https://github.com/spookylukey/django-htmx-patterns
- https://youtube.com/@bugbytes3923

I'll make sure to keep PyHAT in mind when I release any new htmx and Django projects / content in the future, and I'll be sure to contribute them to the awesome-python-htmx collection. Thanks for including my project, and I'm excited to see how PyHAT evolves!

**Comment by benjamin-kirkbride** [comment]
@Tobi-De thanks for your feedback, it's very appreciated! I have added both of resources you mentioned, you are correct they are extremely good, I will definitely need to take the time to go through them all.

As you have expressed interest in getting more involved, would you mind introducing yourself on PyHAT-stack/awesome-python-htmx#2 so we can start getting everyone talking in the same space?
